# vim: ft=sshconfig
## nw.rubykaigi

Host bastion.rubykaigi.net bastion-usw2.rubykaigi.net
  User rk
  Port 9922
  ControlMaster auto
  ControlPath ~/.ssh/master-%r@%h:%p
  ControlPersist 1h


Host *.rubykaigi.net !bastion.rubykaigi.net !bastion-usw2.rubykaigi.net
  ProxyJump bastion.rubykaigi.net
  User rk

Host test-es-*.rubykaigi.net es-*.rubykaigi.net
  PubkeyAcceptedKeyTypes +ssh-rsa
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes

Host *.rubykaigi.net
  User rk

Host *.venue.rubykaigi.net *.nrt.rubykaigi.net *.hnd.rubykaigi.net *.itm.rubykaigi.net *.hot.rubykaigi.net
  HostKeyAlgorithms +ssh-rsa
  KexAlgorithms +diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

Host br-*.rubykaigi.net er-*.rubykaigi.net cs-*.rubykaigi.net as-*.rubykaigi.net
  SetEnv TERM=screen
  #Ciphers +aes256-cbc
