# vim: ft=ruby
cask '1password'
cask 'google-chrome@dev'
cask 'firefox@developer-edition'
cask 'google-drive'
cask 'aquaskk'
cask 'karabiner-elements'
cask 'logseq'
cask 'parsec'
cask 'tailscale'
cask 'logitech-g-hub'
cask 'prolific-pl2303'
cask 'linearmouse'
cask 'the-unarchiver'
cask 'wezterm'
cask 'visual-studio-code@insiders'
cask 'discord@ptb'
cask 'slack'
cask 'spotify'
cask 'vlc'
cask 'wireshark'
cask 'figma'
cask 'zoom'

mas 'Dictionaries', id: 1380563956
mas 'Ivory', id: 6444602274

tap 'jorgelbg/tap'

brew 'gnupg'
brew 'gnu-sed'
brew 'pinentry-touchid'
brew 'pinentry-mac'
brew 'rbenv'
brew 'ruby-build'
brew 'tmux'
brew 'mtr'
